name: Build

on: [push, pull_request]

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        cfg:
          - { CUDA: '11.0', MSVC: true }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Install CMake
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install cmake
    - name: Install Mingw
      uses: crazy-max/ghaction-chocolatey@v1
      if: matrix.cfg.MSVC == false
      with:
        args: install mingw
    - name: Install CUDA Toolkit
      if: matrix.cfg.CUDA == '11.0'
      shell: pwsh
      run: |
        Set-ExecutionPolicy unrestricted
        & '.github\\install-cuda.ps1' -Version '11.0'
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.cfg.MSVC == true
    - name: Create build directory
      shell: pwsh
      run: |
        mkdir build
    - name: Run CMake configure
      if: matrix.cfg.CUDA != '0'
      shell: pwsh
      run: |
        dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0"
